/* auto-generated */

export type ClientScript = 
  | 'charselect'
  | 'criminaltask'
  | 'elevators'
  | 'emotes'
  | 'group'
  | 'hotel'
  | 'hud'
  | 'identities'
  | 'interaction'
  | 'medical'
  | 'megaphone'
  | 'prison'
  | 'radialmenu'
  | 'radio'
  | 'rent'
  | 'robbery'
  | 'roster'
  | 'safezones'
  | 'settings'
  | 'snipets'
  | 'topscore'
  | 'weather'
export type ServerScript = 
  | 'appearance'
  | 'criminaltask'
  | 'db'
  | 'group'
  | 'hotel'
  | 'interaction'
  | 'medical'
  | 'prison'
  | 'robbery'
  | 'roster'
  | 'topscore'
export type WebScript = 
  | 'hud'
  | 'radio'
  | 'roster'
  | 'topscore'
